# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'

- task: Docker@2
  inputs:
    containerRegistry: 'DOCKER-HUB'
    command: 'login'

- task: Docker@2
  inputs:
    containerRegistry: 'DOCKER-HUB'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: Docker@2
  inputs:
    containerRegistry: 'MY-ACR-CONNECTION'
    repository: 'test'
    command: 'buildAndPush'
    Dockerfile: '**/Dockerfile'
- task: PythonScript@0
  inputs:
    scriptSource: 'filePath'
    scriptPath: '$(System.DefaultWorkingDirectory)/clock-script.py'

- task: CopyFiles@2
  inputs:
    Contents: '**'
    TargetFolder: '$(System.DefaultWorkingDirectory)'
- task: PublishBuildArtifacts@1
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'drop'
    publishLocation: 'Container'
